-- Project schema (без данных)

CREATE TABLE User (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(64) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('admin','user') NOT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  pumpControlAccess TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE SetGroup (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE StationSet (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE UserSetGroup (
  user_id INT NOT NULL,
  set_group_id INT NOT NULL,
  PRIMARY KEY (user_id, set_group_id),
  CONSTRAINT fk_usg_user FOREIGN KEY (user_id) REFERENCES User(id) ON DELETE CASCADE,
  CONSTRAINT fk_usg_set_group FOREIGN KEY (set_group_id) REFERENCES SetGroup(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE scd_event (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  station_num INT NOT NULL,
  event_code INT NOT NULL,
  severity ENUM('ERROR','WARNING') NOT NULL,
  message VARCHAR(512) NOT NULL,
  opened_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  closed_at TIMESTAMP NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE trend_data (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  station_num INT NOT NULL,
  tag VARCHAR(128) NOT NULL,
  value DOUBLE NOT NULL,
  ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_station_tag_ts (station_num, tag, ts)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE station_last_values (
  station_num INT NOT NULL,
  tag VARCHAR(128) NOT NULL,
  value DOUBLE NOT NULL,
  ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (station_num, tag)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

